"""HTTP-инфраструктура NC//NET: локализация ошибок, валидация тем,
atomic-enpoint декоратор, query-утилиты (итерация P1-12, логика не менялась)."""
import functools
import re

from core import ApiError


SERVER_ERROR_EN = {
    'Требуется вход в систему': 'Authentication required',
    'Нужен псевдоним (Handle) персонажа': 'Character Handle is required',
    'Новый персонаж должен иметь одну роль с рангом 4': 'A new character must have one Role at Rank 4',
    'Нужно заполнить все 10 характеристик': 'All 10 Characteristics are required',
    'При создании каждая характеристика должна быть от 2 до 8': 'Each Characteristic must be between 2 and 8 at creation',
    'Нужно распределить ровно 62 очка характеристик': 'Allocate exactly 62 Characteristic Points',
    'Нужно распределить ровно 86 очков навыков': 'Allocate exactly 86 Skill Points',
    'Выберите культурный язык с бесплатным уровнем 4': 'Choose a Cultural Language at free Level 4',
    'Культурный язык должен соответствовать происхождению Lifepath': 'Cultural Language must match Lifepath origin',
    'Заполните общий Lifepath': 'Complete the Common Lifepath',
    'Заполните все поля Lifepath выбранной роли': 'Complete every Role-Based Lifepath field',
    'Одновременно допустим только один Neuroport': 'Only one Neuroport is allowed',
    'В 2070-х хром при создании требует Neuroport': 'Cyberware at creation requires a Neuroport',
    'Sell Your Soul требует покровителя и обязательство': 'Sell Your Soul requires a Patron and an Obligation',
    'Нельзя завершить создание с Humanity ниже 0': 'Creation cannot finish below 0 Humanity',
    'Лист персонажа должен быть объектом': 'Character data must be an object',
    'Лист персонажа слишком большой': 'Character data is too large',
    'Некорректный JSON': 'Invalid JSON',
    'Пустое тело запроса': 'Empty request body',
    'Active Role должна достичь Rank 4 перед multiclass': 'Active Role must reach Rank 4 before multiclassing',
    'Active Role должна достичь Rank 4 перед переключением': 'Active Role must reach Rank 4 before switching',
    'Exec должен выбрать стартового сотрудника Teamwork': 'Exec must choose a starting Teamwork Team Member',
    'Medtech распределяет 4 ранга Medicine': 'Medtech must allocate 4 Medicine ranks',
    'Nomad должен заполнить 4 стартовых выбора Moto': 'Nomad must complete 4 starting Moto choices',
    'Role Ability уже достигла Rank 10': 'Role Ability has already reached Rank 10',
    'Role не принадлежит персонажу': 'The character does not have this Role',
    'Role-Based Lifepath разрешён только primary Role': 'Role-Based Lifepath is only allowed for the primary Role',
    'Skill уже достиг Level 10': 'Skill has already reached Level 10',
    'Specialization уже достигла Level 10': 'Specialization has already reached Level 10',
    'Tech распределяет 8 рангов Maker: по 2 за каждый ранг роли': 'Tech must allocate 8 Maker ranks: 2 for each Role rank',
    'cash должен быть числом': 'cash must be numeric',
    'skill_pools должен быть объектом': 'skill_pools must be an object',
    'skill_pools содержит неизвестный специализированный навык': 'skill_pools contains an unknown specialized Skill',
    'skill_specializations должен быть списком до 100 записей': 'skill_specializations must be a list of no more than 100 entries',
    'stats должен быть объектом': 'stats must be an object',
    'Баланс IP не может быть отрицательным': 'IP balance cannot be negative',
    'В корзине нет известных товаров': 'The Cart contains no recognized items',
    'Покупка доступна только из текущего Night Market': 'Purchases are only available from the current Night Market stock',
    'Инвентарь не может содержать больше 500 экземпляров': 'Inventory cannot contain more than 500 item instances',
    'Некорректное количество': 'Invalid quantity',
    'Сначала снимите или извлеките предмет': 'Unequip or uninstall the item first',
    'Inventory должен содержать объекты': 'Inventory entries must be objects',
    'Некорректное состояние предмета': 'Invalid item state',
    'У персонажа не может быть двух одинаковых Roles': 'A character cannot have duplicate Roles',
    'Custom items будут добавлены отдельным этапом; выберите предмет из Database': 'Custom items will be added in a later stage; choose an item from the Database',
    'Предмет находится в неправильном разделе Inventory': 'The item is in the wrong Inventory section',
    'skills должен быть объектом до 500 записей': 'skills must be an object with no more than 500 entries',
    'armor должен быть объектом': 'armor must be an object',
    'Укажите причину изменения Character Sheet': 'Provide a reason for the Character Sheet change',
    'В Character Sheet нет изменений': 'There are no Character Sheet changes',
    'Изменение Character Sheet не найдено': 'Character Sheet change not found',
    'Откат доступен только до следующего изменения Dossier': 'Revert is only available before the next Dossier change',
    'Snapshot для отката повреждён': 'The revert snapshot is corrupted',
    'Некорректный источник получения предмета': 'Invalid item acquisition source',
    'Custom Cyberware требует отдельной механики установки': 'Custom Cyberware requires a dedicated installation system',
    'Custom item требует название': 'Custom item name is required',
    'Некорректная категория custom item': 'Invalid custom item category',
    'stackable должен быть логическим значением': 'stackable must be boolean',
    'Неизвестный предмет: выберите Database item или создайте Custom item': 'Unknown item: choose a Database item or create a Custom item',
    'Этот предмет нельзя экипировать': 'This item cannot be equipped',
    'Используйте действие Equip в Character Sheet': 'Use the Equip action in the Character Sheet',
    'Экземпляр предмета не найден': 'Item instance not found',
    'Этот предмет не является расходником': 'This item is not consumable',
    'Расходник должен быть исправен и находиться при персонаже': 'The consumable must be functional and carried by the character',
    'Недостаточно единиц расходника': 'Not enough consumable units',
    'Экипировать можно только carried предмет': 'Only a carried item can be equipped',
    'Недопустимый режим экипировки': 'Invalid equip mode',
    'Недостаточно свободных рук для экипировки': 'Not enough free hands to equip this item',
    'Недопустимый слот экипировки': 'Invalid equipment slot',
    'Достигнут лимит экипированных копий': 'Equipped copy limit reached',
    'Предмет не экипирован': 'The item is not equipped',
    'Неизвестное действие с предметом': 'Unknown item action',
    'Предмет не поддерживает включение и выключение': 'The item cannot be activated or deactivated',
    'Сначала экипируйте предмет': 'Equip the item first',
    'Предмет уже находится в выбранном состоянии': 'The item is already in the requested state',
    'Effect должен быть объектом': 'Effect must be an object',
    'Effect содержит неподдерживаемые поля': 'Effect contains unsupported fields',
    'Укажите название эффекта': 'Effect name is required',
    'Укажите причину эффекта': 'Effect reason is required',
    'Effect value должен быть от -100 до 100': 'Effect value must be between -100 and 100',
    'Multiply effect должен быть от 0 до 10': 'Multiply effect must be between 0 and 10',
    'Некорректная stacking group': 'Invalid stacking group',
    'Некорректный тип длительности эффекта': 'Invalid effect duration type',
    'Effect value должен быть числом': 'Effect value must be numeric',
    'Effect action содержит неподдерживаемые поля': 'Effect action contains unsupported fields',
    'Effect instance не найден': 'Effect instance not found',
    'Effect instance уже архивирован': 'Effect instance is already archived',
    'Неизвестное действие с эффектом': 'Unknown effect action',
    'Эффект уже отключён': 'Effect is already disabled',
    'Истёкший real-time эффект нельзя включить повторно': 'An expired real-time effect cannot be enabled again',
    'Завершённый round effect нельзя включить повторно': 'A completed round effect cannot be enabled again',
    'Эффект уже включён': 'Effect is already enabled',
    'Tick доступен только для round effect': 'Tick is only available for round effects',
    'Round effect сейчас не активен': 'Round effect is not currently active',
    'Сначала снимите установленные модификации': 'Remove installed modifications first',
    'Повреждена связь установленной модификации': 'Installed modification link is corrupted',
    'Modification содержит неподдерживаемые поля': 'Modification contains unsupported fields',
    'Некорректный host или upgrade instance': 'Invalid host or upgrade instance',
    'Укажите причину установки modification': 'Modification installation reason is required',
    'Host или upgrade не найден в Inventory': 'Host or upgrade was not found in Inventory',
    'Host должен быть исправен и находиться при персонаже': 'Host must be functional and carried by the character',
    'Upgrade должен находиться в состоянии carried': 'Upgrade must be in the carried state',
    'Требуется ручное подтверждение сложного правила совместимости': 'Complex compatibility rule requires manual confirmation',
    'Modification action содержит неподдерживаемые поля': 'Modification action contains unsupported fields',
    'weapon_instance_id допустим только для mount_weapon': 'weapon_instance_id is only allowed for mount_weapon',
    'ammo_instance_id допустим только для Reload': 'ammo_instance_id is only allowed for Reload',
    'Выберите конкретный ammo stack': 'Choose a specific ammo stack',
    'Выберите payload для Gas Jet: street_drug / poison / biotoxin': 'Choose a Gas Jet payload: street_drug / poison / biotoxin',
    'Ammo stack недоступен для Reload': 'Ammo stack is unavailable for Reload',
    'Ammo stack несовместим с этим оружием': 'Ammo stack is incompatible with this weapon',
    'Магазин уже заполнен': 'The magazine is already full',
    'Нельзя смешивать разные типы ammo в одном магазине': 'Different ammo types cannot be mixed in one magazine',
    'В выбранном ammo stack нет боеприпасов': 'The selected ammo stack is empty',
    'Частично использованный ammo stack нельзя продать': 'A partially used ammo stack cannot be sold',
    'Vehicle repair содержит неподдерживаемые поля': 'Vehicle repair contains unsupported fields',
    'Укажите причину Vehicle repair': 'Provide a reason for the Vehicle repair',
    'Vehicle repair уже выполняется': 'A Vehicle repair is already in progress',
    'Vehicle не нуждается в ремонте': 'The Vehicle does not need repair',
    'Укажите техника для Vehicle repair': 'Specify the Vehicle repair technician',
    'Нет активного Vehicle repair': 'There is no active Vehicle repair',
    'Укажите итог Repair Check': 'Provide the Repair Check total',
    'Используйте Vehicle Repair Workflow': 'Use the Vehicle Repair Workflow',
    'Vehicle SDP action поддерживает только damage': 'Vehicle SDP actions only support damage',
    'Modification не найдена': 'Modification not found',
    'Modification уже снята': 'Modification is already removed',
    'Эта modification не может быть снята': 'This modification cannot be removed',
    'Неизвестное действие с modification': 'Unknown modification action',
    'Укажите причину снятия modification': 'Modification removal reason is required',
    'Сначала снимите modifications, зависящие от granted slots': 'Remove modifications that depend on granted slots first',
    'Modification не имеет alternate attack profile': 'Modification has no alternate attack profile',
    'Modification не имеет action resource profile': 'Modification has no action resource profile',
    'Alternate weapon разряжен': 'Alternate weapon is unloaded',
    'Нет боеприпасов для перезарядки alternate weapon': 'No ammunition is available to reload the alternate weapon',
    'Modification не является баллоном NOS': 'Modification is not a NOS tank',
    'Баллон NOS уже использован в этот игровой день': 'This NOS tank was already used this campaign day',
    'Укажите причину сброса NOS': 'Provide a reason for resetting NOS',
    'Баллон NOS уже готов к использованию': 'This NOS tank is already ready to use',
    'Баллон NOS не является оружием': 'A NOS tank is not a weapon',
    'Баллон NOS нельзя перезарядить': 'A NOS tank cannot be reloaded',
    'Для атаки требуется X патронов': 'This attack requires X rounds',
    'Vehicle configuration должна быть объектом': 'Vehicle configuration must be an object',
    'Vehicle configuration содержит неизвестные поля': 'Vehicle configuration contains unknown fields',
    'Выберите допустимое направление mounted weapon': 'Choose an allowed mounted weapon orientation',
    'Выберите обязательную конфигурацию транспорта': 'Choose the required vehicle configuration',
    'Некорректная конфигурация транспорта': 'Invalid vehicle configuration',
    'Повреждена связь Vehicle Heavy Weapon Mount': 'Vehicle Heavy Weapon Mount link is corrupted',
    'Modification не является Vehicle Heavy Weapon Mount': 'Modification is not a Vehicle Heavy Weapon Mount',
    'Укажите причину изменения mounted weapon': 'Provide a reason for changing the mounted weapon',
    'Сначала снимите оружие с Vehicle Heavy Weapon Mount': 'Unmount the weapon from the Vehicle Heavy Weapon Mount first',
    'Сначала снимите текущее mounted weapon': 'Unmount the current weapon first',
    'Выберите конкретный экземпляр оружия': 'Choose a specific weapon instance',
    'Крепление принимает только двуручное дальнобойное оружие': 'The mount only accepts a two-handed ranged weapon',
    'Оружие должно быть свободным и находиться в carried': 'The weapon must be free and in the carried state',
    'Mounted weapon instance отсутствует': 'Mounted weapon instance is missing',
    'Сначала снимите upgrades жилых комнат': 'Remove vehicle room upgrades first',
    'Сначала освободите места, занятые Heavy Weapon Mount': 'Free the seats occupied by Heavy Weapon Mounts first',
    'Housing Capacity требуется для нескольких Heavy Weapon Mounts': 'Housing Capacity is required for multiple Heavy Weapon Mounts',
    'Сначала установите оружие в Vehicle Heavy Weapon Mount': 'Mount a weapon in the Vehicle Heavy Weapon Mount first',
    'Оружие не имеет отслеживаемого магазина': 'The weapon has no tracked magazine',
    'Mounted weapon управляется только через Vehicle Garage': 'Mounted weapons are managed only through the Vehicle Garage',
    'Modification configuration должна быть объектом': 'Modification configuration must be an object',
    'Modification configuration содержит неизвестные поля': 'Modification configuration contains unknown fields',
    'Выберите обязательную конфигурацию modification': 'Choose the required modification configuration',
    'Некорректный вариант configuration': 'Invalid configuration choice',
    'Vehicle configuration пока не поддерживается': 'Vehicle configuration is not supported yet',
    'Cyberdeck configuration пока не поддерживается': 'Cyberdeck configuration is not supported yet',
    'Сначала освободите зависимые Cyberdeck slots': 'Free dependent Cyberdeck slots first',
    'Program action содержит неподдерживаемые поля': 'Program action contains unsupported fields',
    'Installed Program instance не найден': 'Installed Program instance not found',
    'Повреждена связь установленной Program': 'Installed Program link is corrupted',
    'Укажите причину Program action': 'Provide a reason for the Program action',
    'Backup restore содержит неподдерживаемые поля': 'Backup restore contains unsupported fields',
    'Installed Backup Drive не найден': 'Installed Backup Drive not found',
    'Backup Drive не содержит Programs': 'Backup Drive contains no Programs',
    'Укажите причину Backup restore': 'Provide a reason for Backup restore',
    'Installed Defense Sequencer не найден': 'Installed Defense Sequencer not found',
    'Defense Sequencer не имеет pending Armor trigger': 'Defense Sequencer has no pending Armor trigger',
    'Выбранная Armor не входит в pending eligibility snapshot': 'The selected Armor is not in the pending eligibility snapshot',
    'Eligible Armor больше не установлена в этом Cyberdeck': 'The eligible Armor is no longer installed in this Cyberdeck',
    'Defense Sequencer может Rez только inactive Armor': 'Defense Sequencer can Rez only inactive Armor',
    'Другая копия Armor уже Rezzed': 'Another Armor copy is already Rezzed',
    'Defense Sequencer resolution содержит неподдерживаемые поля': 'Defense Sequencer resolution contains unsupported fields',
    'Подтвердите, что выбранная Armor не использовалась в этом Netrun': 'Confirm that the selected Armor was not used during this Netrun',
    'Выберите concrete Armor Program instance': 'Choose a concrete Armor Program instance',
    'Укажите причину Defense Sequencer resolution': 'Provide a reason for the Defense Sequencer resolution',
    'Black ICE не имеет curated STAT effect': 'Black ICE has no curated STAT effect',
    'Black ICE STAT penalty roll должен быть от 1 до 6': 'Black ICE STAT penalty roll must be from 1 to 6',
    'Сначала удалите Cyberware через audited Uninstall': 'Remove Cyberware through the audited Uninstall action first',
    'Изменяйте Cyberware installation только через lifecycle action': 'Change Cyberware installation only through a lifecycle action',
    'Изменяйте concrete Cyberware hosts только через lifecycle action': 'Change concrete Cyberware hosts only through a lifecycle action',
    'Cyberware action содержит неподдерживаемые поля': 'Cyberware action contains unsupported fields',
    'Укажите причину Cyberware lifecycle action': 'Provide a reason for the Cyberware lifecycle action',
    'Cyberware instance не найден': 'Cyberware instance not found',
    'Cyberware instance не связан с Data Pool': 'Cyberware instance is not linked to the Data Pool',
    'host_instance_ids должен быть коротким списком': 'host_instance_ids must be a short list',
    'Некорректный concrete Cyberware host': 'Invalid concrete Cyberware host',
    'Cyberware уже установлена': 'Cyberware is already installed',
    'Сломанную Cyberware нельзя установить': 'Broken Cyberware cannot be installed',
    'Эта Cyberware не использует Option host': 'This Cyberware does not use an Option host',
    'Допустима только одна установленная копия Cyberware': 'Only one installed Cyberware copy is allowed',
    'Недостаточно Humanity для установки Cyberware': 'Not enough Humanity to install Cyberware',
    'Rebind требует установленную Cyberware Option': 'Rebind requires an installed Cyberware Option',
    'Cyberware уже не установлена': 'Cyberware is already uninstalled',
    'Стартовый Neuroport нельзя извлечь этим действием': 'The starting Neuroport cannot be removed with this action',
    'Одновременно допустим только один Cyberaudio Suite': 'Only one Cyberaudio Suite may be installed at a time',
    'Paired Cyberlegs требуют обе свободные стороны': 'Paired Cyberlegs require both sides to be free',
    'Изменяйте Cyberware side только через lifecycle action': 'Change Cyberware side only through a lifecycle action',
    'Подтвердите manual surgery/service resolution': 'Confirm manual surgery/service resolution',
    'Укажите clinic, surgeon или technician': 'Specify a clinic, surgeon, or technician',
    'Подтвердите required Biosystem': 'Confirm the required Biosystem',
    'Эта Cyberware не использует left/right side': 'This Cyberware does not use a left/right side',
    'Configure side требует установленный sided foundation': 'Configure side requires an installed sided foundation',
    'Выберите installation side: left/right': 'Choose installation side: left/right',
    'Quick Detach требует установленный Cyberarm': 'Quick Detach requires an installed Cyberarm',
    'Cyberarm не имеет установленный Quick Change Mount': 'Cyberarm has no installed Quick Change Mount',
    'Quick Attach требует detached Quick Change Cyberarm': 'Quick Attach requires a detached Quick Change Cyberarm',
    'Quick Change Cyberarm bundle повреждён': 'Quick Change Cyberarm bundle is corrupted',
    'Therapy action содержит неподдерживаемые поля': 'Therapy action contains unsupported fields',
    'Укажите причину Therapy action': 'Provide a reason for the Therapy action',
    'Therapy course уже активен': 'A Therapy course is already active',
    'Неизвестный Therapy type': 'Unknown Therapy type',
    'Укажите therapist или clinic': 'Specify a therapist or clinic',
    'Недостаточно средств для Therapy': 'Not enough funds for Therapy',
    'Humanity уже достигла Therapy maximum': 'Humanity has already reached the Therapy maximum',
    'Укажите addiction для Therapy': 'Specify the addiction for Therapy',
    'Нет активного Therapy course': 'There is no active Therapy course',
    'Therapy profile повреждён': 'Therapy profile is corrupted',
    'Подтвердите завершение недели Therapy': 'Confirm completion of the Therapy week',
    'Сначала освободите зависимые Cyberware Option Slots': 'Free dependent Cyberware Option Slots first',
    'Cyberweapon action содержит неподдерживаемые поля': 'Cyberweapon action contains unsupported fields',
    'Укажите причину Cyberweapon action': 'Provide a reason for the Cyberweapon action',
    'Installed curated Cyberweapon не найден': 'Installed curated Cyberweapon not found',
    'Cyberweapon не имеет deploy/stow state': 'Cyberweapon has no deploy/stow state',
    'Cyberweapon не имеет rev action': 'Cyberweapon has no rev action',
    'Сначала deploy Cyberweapon': 'Deploy the Cyberweapon first',
    'Fire доступен только ranged Cyberweapon': 'Fire is available only for a ranged Cyberweapon',
    'Cyberweapon magazine пуст': 'Cyberweapon magazine is empty',
    'Cyberweapon не использует tracked ammo': 'Cyberweapon does not use tracked ammunition',
    'Ammo stack несовместим с Cyberweapon': 'Ammo stack is incompatible with the Cyberweapon',
    'Повреждена связь Popup Cyberweapon': 'Popup Cyberweapon binding is corrupted',
    'Permanent Popup Weapon attachments нельзя изменять': 'Permanent Popup Weapon attachments cannot be changed',
    'Popup Weapon binding содержит неподдерживаемые поля': 'Popup Weapon binding contains unsupported fields',
    'Подтвердите permanent Popup Weapon binding': 'Confirm permanent Popup Weapon binding',
    'Укажите причину Popup Weapon binding': 'Provide a reason for Popup Weapon binding',
    'Installed generic Popup Weapon option не найден': 'Installed generic Popup Weapon option not found',
    'Popup Weapon уже имеет permanent bound weapon': 'Popup Weapon already has a permanent bound weapon',
    'Permanent Popup Weapon binding нельзя продать отдельно': 'Permanent Popup Weapon binding cannot be sold separately',
    'Повреждена связь Armor/Shield Tech Upgrade': 'Armor/Shield Tech Upgrade binding is corrupted',
    'Armor Tech Upgrade содержит неподдерживаемые поля': 'Armor Tech Upgrade contains unsupported fields',
    'Подтвердите успешный Tech Upgrade Check': 'Confirm a successful Tech Upgrade Check',
    'Укажите Tech и причину Armor Upgrade': 'Specify the Tech and Armor Upgrade reason',
    'Concrete Armor/Shield instance не найден': 'Concrete Armor/Shield instance not found',
    'Armor/Shield уже имеет Tech Upgrade': 'Armor/Shield already has a Tech Upgrade',
    'Armor instance не имеет upgradeable SP': 'Armor instance has no upgradeable SP',
    'Permanent Armor Tech Upgrade нельзя продать отдельно': 'Permanent Armor Tech Upgrade cannot be sold separately',
    'Повреждена связь Armor Repair Workflow': 'Armor Repair Workflow binding is corrupted',
    'Armor Repair action содержит неподдерживаемые поля': 'Armor Repair action contains unsupported fields',
    'Укажите причину Armor Repair action': 'Provide a reason for the Armor Repair action',
    'Concrete Armor instance не найден': 'Concrete Armor instance not found',
    'Bulletproof Shields не подлежат ремонту': 'Bulletproof Shields cannot be repaired',
    'Эта Armor не может восстанавливать SP': 'This Armor cannot restore SP',
    'Armor Repair уже активен': 'Armor Repair is already active',
    'Armor должна быть экипирована и повреждена': 'Armor must be equipped and damaged',
    'Укажите Armor repair technician': 'Specify the Armor repair technician',
    'Jeeves Executive Garment Bag недоступен': 'Jeeves Executive Garment Bag is unavailable',
    'Jeeves не ремонтирует Luxury/Super Luxury Armor': 'Jeeves cannot repair Luxury or Super Luxury Armor',
    'Нет активного Armor Repair': 'There is no active Armor Repair',
    'Подтвердите завершение Armor Repair': 'Confirm completion of Armor Repair',
    'Armor не имеет daily self-repair': 'Armor has no daily self-repair',
    'Подтвердите день без потери SP': 'Confirm a day without losing SP',
    'Повреждена связь Popup Shield': 'Popup Shield binding is corrupted',
    'Popup Shield action содержит неподдерживаемые поля': 'Popup Shield action contains unsupported fields',
    'Укажите причину Popup Shield action': 'Provide a reason for the Popup Shield action',
    'Installed Popup Shield option не найден': 'Installed Popup Shield option not found',
    'Сначала извлеките concrete Popup Shield': 'Remove the concrete Popup Shield first',
    'Popup Shield уже содержит concrete shield': 'Popup Shield already contains a concrete shield',
    'Popup Shield принимает только free Bulletproof Shield': 'Popup Shield accepts only a free Bulletproof Shield',
    'Popup Shield не содержит concrete shield': 'Popup Shield contains no concrete shield',
    'Destroyed Shield нельзя deploy': 'A destroyed Shield cannot be deployed',
    'Укажите Popup Shield damage 1–100': 'Provide Popup Shield damage from 1 to 100',
    'Укажите bounded Armor Repair service cost': 'Provide a bounded Armor Repair service cost',
    'Подтвердите оплату Armor Repair service': 'Confirm payment for the Armor Repair service',
    'Недостаточно средств для Armor Repair service': 'Not enough funds for the Armor Repair service',
    'Run доступен только Attacker Program': 'Run is available only for an Attacker Program',
    'Saved Program instance недоступен для восстановления': 'Saved Program instance is unavailable for restore',
    'Недостаточно Cyberdeck slots для Backup restore': 'Not enough Cyberdeck slots for Backup restore',
    'Black ICE требует NET entity deployment': 'Black ICE requires NET entity deployment',
    'Activate доступен только Booster или Defender Program': 'Activate is available only for Booster or Defender Programs',
    'Program необходимо сначала Deactivate': 'Deactivate the Program first',
    'REZ damage требует Rezzed Program': 'REZ damage requires a Rezzed Program',
    'Укажите REZ damage от 1 до 100': 'Provide REZ damage from 1 to 100',
    'Только одна копия этой Program может быть Rezzed': 'Only one copy of this Program may be Rezzed',
    'Derez требует Rezzed Program': 'Derez requires a Rezzed Program',
    'Deactivate требует Rezzed или Derezzed Program': 'Deactivate requires a Rezzed or Derezzed Program',
    'Black ICE deployment содержит неподдерживаемые поля': 'Black ICE deployment contains unsupported fields',
    'Installed Black ICE instance не найден': 'Installed Black ICE instance not found',
    'Выбранная Program не является Black ICE': 'The selected Program is not Black ICE',
    'Для этой Black ICE уже существует active NET entity': 'This Black ICE already has an active NET entity',
    'Black ICE необходимо сначала Deactivate': 'Deactivate Black ICE first',
    'Укажите Floor для Black ICE': 'Specify a Floor for Black ICE',
    'Укажите target для deployed Black ICE': 'Specify a target for deployed Black ICE',
    'Укажите причину Black ICE deployment': 'Provide a reason for Black ICE deployment',
    'NET entity action содержит неподдерживаемые поля': 'NET entity action contains unsupported fields',
    'Black ICE NET entity не найдена': 'Black ICE NET entity not found',
    'Black ICE NET entity уже завершена': 'Black ICE NET entity is already completed',
    'Source Black ICE installation отсутствует': 'Source Black ICE installation is missing',
    'Укажите причину NET entity action': 'Provide a reason for the NET entity action',
    'REZ damage требует active Black ICE': 'REZ damage requires active Black ICE',
    'Slide требует hunting Black ICE': 'Slide requires hunting Black ICE',
    'Engage требует lying-in-wait Black ICE': 'Engage requires lying-in-wait Black ICE',
    'Укажите Floor и target для Black ICE': 'Specify a Floor and target for Black ICE',
    'Session NET entity link отсутствует': 'Session NET entity link is missing',
    'Нет права редактировать Session NET Floors': 'No permission to edit Session NET Floors',
    'NET Floor требует label': 'NET Floor requires a label',
    'Укажите причину изменения NET Floors': 'Provide a reason for changing NET Floors',
    'NET Floor уже существует или достигнут лимит': 'NET Floor already exists or the limit was reached',
    'Session NET Floor не найден': 'Session NET Floor not found',
    'NET Floor используется active entity': 'NET Floor is used by an active entity',
    'Нет права управлять Session NET Queue': 'No permission to manage the Session NET Queue',
    'Некорректный Session NET turn state': 'Invalid Session NET turn state',
    'Укажите причину изменения NET Queue': 'Provide a reason for changing the NET Queue',
    'Session NET snapshot для отката повреждён': 'Session NET revert snapshot is corrupted',
    'Session NET context изменён после Character action': 'Session NET context changed after the Character action',
    'Некорректная Live Session': 'Invalid Live Session',
    'Нет доступа к Live NET Session': 'No access to the Live NET Session',
    'Character не участвует в этой Session': 'Character does not participate in this Session',
    'Выберите validated Session NET Floor': 'Choose a validated Session NET Floor',
    'Нет права управлять Black ICE entity': 'No permission to manage the Black ICE entity',
    'Выберите Session target combatant': 'Choose a Session target combatant',
    'Некорректный Session target для Black ICE': 'Invalid Session target for Black ICE',
    'Выберите validated Session Floor и target': 'Choose a validated Session Floor and target',
    'Сначала удалите NET nodes с этого Floor': 'Delete NET nodes from this Floor first',
    'Нет права редактировать NET Architecture': 'No permission to edit NET Architecture',
    'NET node содержит неподдерживаемые поля': 'NET node contains unsupported fields',
    'NET node требует validated Floor': 'NET node requires a validated Floor',
    'Некорректный NET node type или label': 'Invalid NET node type or label',
    'Укажите причину изменения NET Architecture': 'Provide a reason for changing NET Architecture',
    'Достигнут лимит NET nodes': 'NET node limit reached',
    'NET node не найден': 'NET node not found',
    'Сначала удалите NET paths этого node': 'Delete NET paths connected to this node first',
    'NET node используется active entity': 'NET node is used by an active entity',
    'NET path содержит неподдерживаемые поля': 'NET path contains unsupported fields',
    'Некорректные NET path endpoints или direction': 'Invalid NET path endpoints or direction',
    'NET path уже существует': 'NET path already exists',
    'Достигнут лимит NET paths': 'NET path limit reached',
    'NET path не найден': 'NET path not found',
    'Выберите validated Session NET node': 'Choose a validated Session NET node',
    'Выберите validated Session Floor, node и target': 'Choose a validated Session Floor, node, and target',
    'Live NET Session не найдена': 'Live NET Session not found',
    'NET action содержит неподдерживаемые поля': 'NET action contains unsupported fields',
    'NET action требует Character combatant': 'NET action requires a Character combatant',
    'Character для NET action не найден': 'Character for NET action not found',
    'Нет права выполнять NET action этим Character': 'No permission to perform a NET action with this Character',
    'NET action требует Netrunner Role': 'NET action requires the Netrunner Role',
    'Укажите причину NET action': 'Provide a reason for the NET action',
    'Jack In требует Access Point node': 'Jack In requires an Access Point node',
    'Access Point node ещё не revealed': 'Access Point node is not revealed yet',
    'Netrunner не Jacked In': 'Netrunner is not Jacked In',
    'NET action требует Jacked In Netrunner': 'NET action requires a Jacked In Netrunner',
    'Move требует revealed target node': 'Move requires a revealed target node',
    'NET nodes не соединены revealed path': 'NET nodes are not connected by a revealed path',
    'Unresolved Password блокирует движение вперёд': 'Unresolved Password blocks forward movement',
    'Pathfinder target node не найден': 'Pathfinder target node not found',
    'Pathfinder target должен быть adjacent node': 'Pathfinder target must be an adjacent node',
    'Backdoor требует текущий Password node': 'Backdoor requires the current Password node',
    'Eye-Dee доступен только для текущего node': 'Eye-Dee is available only for the current node',
    'Control action требует текущий Control node': 'Control action requires the current Control node',
    'Program Attack требует Black ICE на текущем node': 'Program Attack requires Black ICE on the current node',
    'Program Attack target entity недоступна': 'Program Attack target entity is unavailable',
    'Program Attack требует installed Attacker Program': 'Program Attack requires an installed Attacker Program',
    'NET Action budget исчерпан для текущего NET Round': 'NET Action budget is exhausted for the current NET Round',
    'Target Dossier изменён в другой вкладке': 'Target Dossier changed in another tab',
    'Нет допустимых Programs для curated Black ICE effect': 'No eligible Programs for the curated Black ICE effect',
    'Выбранная target Program недопустима': 'Selected target Program is not eligible',
    'Нет права выполнять Black ICE attack': 'No permission to perform a Black ICE attack',
    'Black ICE attack содержит неподдерживаемые поля': 'Black ICE attack contains unsupported fields',
    'Black ICE attack требует active target link': 'Black ICE attack requires an active target link',
    'Source Black ICE Character отсутствует': 'Source Black ICE Character is missing',
    'Black ICE attack требует hunting entity': 'Black ICE attack requires a hunting entity',
    'Source Black ICE Program отсутствует': 'Source Black ICE Program is missing',
    'Black ICE target требует Netrunner Character': 'Black ICE target requires a Netrunner Character',
    'Black ICE target должен быть Jacked In на том же node': 'Black ICE target must be Jacked In on the same node',
    'Black ICE target не имеет Interface Rank': 'Black ICE target has no Interface Rank',
    'Укажите причину Black ICE attack': 'Provide a reason for the Black ICE attack',
    'Нет Rezzed Programs для Anti-Program Black ICE': 'No Rezzed Programs are available for Anti-Program Black ICE',
    'Anti-Program Black ICE effect требует manual resolution': 'Anti-Program Black ICE effect requires manual resolution',
    'Выбранная target Program не является Rezzed': 'Selected target Program is not Rezzed',
    'Неподдерживаемый тип modification host': 'Unsupported modification host type',
    'Сначала снимите зависимые vehicle upgrades': 'Remove dependent vehicle upgrades first',
    'Vehicle instance не найден': 'Vehicle instance not found',
    'Все слоты заняты': 'All slots are filled',
    'Вы уже записаны': 'You are already signed up',
    'Для специализированного навыка повышайте parent-pool': 'Increase the parent pool for a specialized Skill',
    'Достигнут лимит хранилища изображений': 'Image storage limit reached',
    'Заголовок и текст обязательны': 'Title and body are required',
    'Заказ закрыт': 'This Job is closed',
    'Заказ не найден': 'Job not found',
    'Изображение не найдено': 'Image not found',
    'Изображение приватное': 'This image is private',
    'Изображение уже прикреплено': 'Image is already attached',
    'Контраст текста темы должен быть не ниже 4.5:1': 'Theme text contrast must be at least 4.5:1',
    'Логин: 3–24 символа, латиница/цифры/._-': 'Username: 3–24 Latin letters, digits, or ._-',
    'Локация брони не экипирована': 'No Armor is equipped at this location',
    'Можно удалять только свои посты': 'You can only delete your own posts',
    'Название и описание обязательны': 'Title and description are required',
    'Не найдено': 'Not found',
    'Неверный логин или пароль': 'Invalid username or password',
    'Недопустимое изображение персонажа': 'Invalid character image',
    'Недопустимое разрешение изображения': 'Invalid image dimensions',
    'Недопустимый тип изображения': 'Invalid image type',
    'Недопустимый щит': 'Invalid shield',
    'Неизвестная Role': 'Unknown Role',
    'Неизвестный parent Skill': 'Unknown parent Skill',
    'Неизвестный ресурс': 'Unknown resource',
    'Неизвестный тип улучшения': 'Unknown advancement type',
    'Некорректная тема': 'Invalid theme',
    'Нельзя записаться на свой заказ': 'You cannot sign up for your own Job',
    'Нет права изменять этого персонажа': 'You do not have permission to modify this character',
    'Нет свободных parent points': 'No free parent points',
    'Новость не найдена': 'Report not found',
    'Ожидается JPEG, PNG или WebP': 'Expected a JPEG, PNG, or WebP image',
    'Оружие не найдено': 'Weapon not found',
    'Пароль: минимум 4 символа': 'Password must contain at least 4 characters',
    'Персонаж не найден': 'Character not found',
    'Персонаж приватный': 'This character is private',
    'Повреждённые данные изображения': 'Corrupted image data',
    'Повышать можно только active Role': 'Only the active Role can be advanced',
    'Предмет не найден': 'Item not found',
    'Предмет не найден в инвентаре': 'Item not found in Inventory',
    'Пустая корзина': 'The Cart is empty',
    'Слишком большая сумма': 'Amount is too large',
    'Некорректная сумма': 'Invalid amount',
    'Некорректное время события': 'Invalid event time',
    'Некорректная локация Night City': 'Invalid Night City location',
    'Слишком много персонажей (максимум 50)': 'Too many characters (maximum 50)',
    'Сначала отсоедините изображение': 'Detach the image first',
    'Статус: open/closed': 'Status must be open or closed',
    'Такой логин уже занят': 'That username is already taken',
    'Тело запроса слишком большое': 'Request body is too large',
    'Только автор может менять статус': 'Only the author can change the status',
    'Только автор может удалить заказ': 'Only the author can delete this Job',
    'Только для пользователей с ролью ГМ': 'GM role required',
    'Укажите parent и specialization': 'Specify parent and specialization',
    'Укажите ненулевое изменение IP и причину': 'Specify a nonzero IP change and a reason',
    'Файл изображения не найден': 'Image file not found',
    'Формат изображения не подтверждён содержимым': 'The image content does not match a supported format',
    'Экипированный щит отсутствует в стартовой закупке': 'The equipped shield is missing from starting purchases',
    'Это не ваш персонаж': 'This is not your character',
    'Только для администраторов NC//NET': 'NC//NET Admin role required',
    'Роли аккаунтов назначает только администратор NC//NET': 'Only an NC//NET Admin can assign account roles',
    'Укажите причину изменения доступа': 'Provide a reason for the access change',
    'Некорректные настройки уведомлений': 'Invalid notification settings',
    'Пользователь не найден': 'User not found',
    'Недопустимая роль аккаунта': 'Invalid account role',
    'Нельзя снять роль с последнего администратора': 'The last Admin cannot be demoted',
    'Handle персоны: 3–40 латинских символов, цифр или ._-': 'Persona Handle: 3–40 Latin letters, digits, or ._-',
    'Персоне нужно отображаемое имя': 'Persona display name is required',
    'Некорректный тип, доступ или статус персоны': 'Invalid Persona kind, access, or status',
    'Некорректный цвет персоны': 'Invalid Persona color',
    'Недопустимое изображение NC//NET': 'Invalid NC//NET image',
    'Изображение принадлежит другому аккаунту': 'Image belongs to another account',
    'VK OAuth не настроен': 'VK OAuth is not configured',
    'Некорректный или истёкший VK OAuth state': 'Invalid or expired VK OAuth state',
    'VK OAuth не вернул пользователя': 'VK OAuth did not return a user',
    'VK OAuth временно недоступен': 'VK OAuth is temporarily unavailable',
    'Только Admin создаёт системные персоны': 'Only an Admin can create System Personas',
    'Только Admin редактирует системные персоны': 'Only an Admin can edit System Personas',
    'Персона не найдена': 'Persona not found',
    'Нет права редактировать эту персону': 'You cannot edit this Persona',
    'Такой Handle персоны уже занят': 'That Persona Handle is already taken',
    'Нужно название сюжетной линии': 'Storyline title is required',
    'Некорректный статус сюжетной линии': 'Invalid Storyline status',
    'Сюжетная линия не найдена': 'Storyline not found',
    'Нет права редактировать эту сюжетную линию': 'You cannot edit this Storyline',
    'Некорректная сюжетная линия': 'Invalid Storyline',
    'Событие хронологии не может быть пустым': 'Timeline event cannot be empty',
    'Контракту нужно название': 'Contract title is required',
    'Некорректный статус, риск или награда контракта': 'Invalid Contract status, risk, or reward',
    'Контракт не найден': 'Contract not found',
    'Нет права редактировать этот контракт': 'You cannot edit this Contract',
    'Контракт недоступен для записи': 'Contract is not open for signup',
    'Завершённый контракт хранит неизменяемый состав': 'A finished Contract preserves its historical Crew',
    'Этот персонаж уже записан': 'This Character is already signed up',
    'Запись на контракт не найдена': 'Contract signup not found',
    'Размер команды меньше уже записанного Crew': 'Crew Capacity is below the current Crew size',
    'Архивное досье доступно только для чтения': 'Archived Dossier is read-only',
    'Архивное досье нельзя записать на контракт': 'Archived Dossier cannot join a Contract',
    'Архивное досье нельзя использовать как автора': 'Archived Dossier cannot publish content',
    'Aftermath уже опубликован или контракт не активен': 'Aftermath is already published or the Contract is not active',
    'Недоступный NPC template': 'Unavailable NPC template',
    'NPC template не найден': 'NPC template not found',
    'Нет права редактировать NPC template': 'You cannot edit this NPC template',
    'Некорректный NPC template': 'Invalid NPC template',
    'NPC template нужно имя': 'NPC template requires a name',
    'Некорректные данные участника сессии': 'Invalid session combatant data',
    'Участник сессии не найден': 'Session combatant not found',
    'Недоступная персона в контракте': 'Unavailable Persona in Contract',
    'Недоступная сюжетная линия': 'Unavailable Storyline',
    'Выберите одного автора публикации': 'Choose exactly one post author',
    'Некорректный формат публикации': 'Invalid post format',
    'Публикации нужен текст и, для длинного формата, заголовок': 'Post body and, for long formats, headline are required',
    'Публикация не найдена': 'Post not found',
    'Нет права редактировать эту публикацию': 'You cannot edit this post',
    'Некорректная публикация': 'Invalid post',
    'Некорректный GM truth status': 'Invalid GM truth status',
    'Укажите причину скрытия': 'Provide a reason for hiding this content',
    'Комментарий не может быть пустым': 'Comment cannot be empty',
    'Комментарий не найден': 'Comment not found',
    'Недоступная персона-автор': 'Unavailable author Persona',
    'Родительский комментарий не найден': 'Parent comment not found',
    'NPC template нужно имя': 'NPC template name is required',
    'Некорректный NPC template': 'Invalid NPC template',
    'Сессия не найдена': 'Session not found',
    'Нет права редактировать сессию': 'You cannot edit this Session',
    'Нет права управлять доступом сессии': 'You cannot manage Session access',
    'Некорректная роль участника сессии': 'Invalid Session member role',
    'Назначение доступа не найдено': 'Session access assignment not found',
    'Assistant может менять только ход и раунд': 'Assistant can only change the turn and round',
    'Safety signal отключён для этой сессии': 'Safety signals are disabled for this Session',
    'Некорректный тип Safety signal': 'Invalid Safety signal type',
    'Нет права управлять Safety signal': 'You cannot manage Safety signals',
    'Safety signal не найден': 'Safety signal not found',
    'Некорректный статус Safety signal': 'Invalid Safety signal status',
    'Resolved Safety signal нельзя открыть повторно': 'A resolved Safety signal cannot be reopened',
    'Некорректный статус сессии': 'Invalid Session status',
    'Участнику сессии нужно имя': 'Session combatant name is required',
    'Нет права редактировать участника': 'You cannot edit this combatant',
    'Нет доступа к экрану сессии': 'You cannot access this Session view',
    'Нет доступа к контракту сессии': 'You cannot access the Session Contract',
    'Нет права завершить контракт': 'You cannot complete this Contract',
    'Результат контракта: completed/failed': 'Contract result must be completed or failed',
    'Выберите доступную персону для Aftermath': 'Choose an available Persona for the Aftermath',
    'Изменение досье должно быть объектом': 'Dossier update must be an object',
    'patch должен быть объектом': 'patch must be an object',
    'Механические поля изменяются только специальными операциями': 'Mechanical fields can only be changed through dedicated operations',
    'public должен быть логическим значением': 'public must be a boolean',
    'Укажите одну конкретную запись: signup_id или character_id': 'Specify exactly one signup: signup_id or character_id',
    'Связать публикацию с контрактом может его GM или участник Crew': 'Only the Contract GM or a Crew member can link a post to it',
    'Сюжетную линию может связать её GM или Crew связанного контракта': 'Only the Storyline GM or Crew of its linked Contract can link a post to it',
    'Награды должны быть списком до 100 записей': 'Rewards must be a list of no more than 100 entries',
    'Некорректная награда': 'Invalid reward',
    'Награду может получить только персонаж из Crew': 'Only a Crew character can receive a reward',
    'Награда персонажа указана дважды': 'A character reward was specified twice',
    'Некорректная сумма награды': 'Invalid reward amount',
    'Награды Cash и IP должны быть неотрицательными числами, IP — целым': 'Cash and IP rewards must be nonnegative numbers, and IP must be an integer',
    'Архивное досье не может получить награду': 'An archived Dossier cannot receive a reward',
    'Деньги изменяются только через Market, Payroll или Aftermath': 'Cash can only be changed through Market, Payroll, or Aftermath',
    'Legacy API доступен только для чтения; используйте NC//NET City Feed': 'Legacy API is read-only; use NC//NET City Feed',
    'Legacy API доступен только для чтения; используйте NC//NET Contracts': 'Legacy API is read-only; use NC//NET Contracts',
    'visibility должен быть объектом': 'visibility must be an object',
    'Некорректные настройки видимости Dossier': 'Invalid Dossier visibility settings',
    'Регистрация новых аккаунтов отключена': 'New account registration is disabled',
    'Пароль: минимум 8 символов': 'Password must contain at least 8 characters',
    'Пароль слишком длинный': 'Password is too long',
    'Приглашение не найдено': 'Invite not found',
    'Приглашение недействительно или уже использовано': 'Invite is invalid or has already been used',
    'Аккаунт отключён администратором': 'Account has been disabled by an administrator',
    'Сессия входа не найдена': 'Login session not found',
    'Текущую сессию завершайте обычным выходом': 'Use regular sign out for the current session',
    'Текущий пароль указан неверно': 'Current password is incorrect',
    'Новый пароль должен отличаться от текущего': 'New password must differ from the current password',
    'Нельзя отключить собственный аккаунт': 'You cannot disable your own account',
    'Нельзя отключить последнего активного администратора': 'The last active administrator cannot be disabled',
    'Укажите revision Dossier': 'Dossier revision is required',
    'Dossier изменён в другой вкладке; обновите страницу': 'Dossier changed in another tab; reload the page',
    'Слишком много запросов; попробуйте позже': 'Too many requests; try again later',
    'Слишком много неудачных входов; попробуйте позже': 'Too many failed sign-in attempts; try again later',
    'Memorial уже опубликован': 'Memorial is already published',
    'Только владелец персонажа заполняет memorial': 'Only the character owner may fill the memorial',
    'Membership требует member и organization persona': 'Membership requires a member and an organization persona',
    'Membership не найден': 'Membership not found',
    'Укажите организацию': 'Specify an organization',
    'Нет доступа к репутации персонажа': 'No access to this character reputation',
    'Действие: store или take': 'Action: store or take',
    'Предмет не найден в личном тайнике': 'Item not found in personal stash',
    'Сначала снимите предмет': 'Unequip the item first',
    'Нет права синхронизировать сессию': 'No permission to sync session',
    'PDF обязателен (base64)': 'PDF is required (base64)',
    'Некорректный base64': 'Invalid base64',
    'Файл не является PDF': 'File is not a PDF',
    'PDF слишком большой (макс 5 МБ)': 'PDF is too large (max 5 MB)',
    'Ошибка парсинга PDF': 'PDF parsing error',
    'Недопустимый источник запроса': 'Invalid request origin',
    'Tech Maker modification содержит неподдерживаемые поля': 'Tech Maker modification contains unsupported fields',
    'Укажите название Tech Maker modification': 'Tech Maker modification name is required',
    'Укажите Tech и причину Tech Maker modification': 'Provide the Tech and a reason for the Tech Maker modification',
    'Выберите конкретный host instance': 'Choose a specific host instance',
    'Host instance не найден': 'Host instance not found',
    'Host не поддерживает Tech Maker modifications': 'The host does not support Tech Maker modifications',
    'Tech Maker effect должен быть объектом': 'Tech Maker effect must be an object',
    'Tech Maker effect содержит неподдерживаемые поля': 'Tech Maker effect contains unsupported fields',
    'Недопустимый Tech Maker effect target': 'Invalid Tech Maker effect target',
    'Tech Maker effect value должен быть целым числом': 'Tech Maker effect value must be an integer',
    'Tech Maker modification требует effect или manual_rule': 'Tech Maker modification requires an effect or a manual rule',
    'Подтвердите успешный Tech Maker Check за столом': 'Confirm the successful Tech Maker Check at the table',
    'Host уже имеет Tech Maker modification этого типа': 'The host already has a Tech Maker modification of this type',
    'Достигнут лимит Tech Maker modifications': 'Tech Maker modification limit reached',
    'Tech Maker action содержит неподдерживаемые поля': 'Tech Maker action contains unsupported fields',
    'Укажите причину Tech Maker action': 'Provide a reason for the Tech Maker action',
    'Tech Maker modification не найдена': 'Tech Maker modification not found',
    'Permanent Tech Maker modification нельзя снять': 'A permanent Tech Maker modification cannot be removed',
    'Tech Maker modification уже снята': 'Tech Maker modification is already removed',
    'Повреждена запись Tech Maker modification': 'Tech Maker modification record is corrupted',
    'Повреждена связь Tech Maker modification': 'Tech Maker modification link is corrupted',
    'Повреждена история Tech Maker modifications': 'Tech Maker modification history is corrupted',
    'Tech Maker fabrication содержит неподдерживаемые поля': 'Tech Maker fabrication contains unsupported fields',
    'Укажите название, Tech и причину Tech Maker fabrication': 'Provide a name, Tech, and reason for the Tech Maker fabrication',
    'Неизвестный blueprint item': 'Unknown blueprint item',
    'Этот предмет нельзя изготовить через Fabrication Expertise': 'This item cannot be fabricated with Fabrication Expertise',
    'Blueprint fabrication требует maker_specialty fabrication': 'Blueprint fabrication requires maker_specialty fabrication',
    'Fabrication Expertise требует blueprint item': 'Fabrication Expertise requires a blueprint item',
    'Некорректная стоимость материалов': 'Invalid material cost',
    'Campaign Clock содержит неподдерживаемые поля': 'Campaign Clock contains unsupported fields',
    'Укажите причину изменения Campaign Clock': 'Provide a reason for changing the Campaign Clock',
    'Укажите либо advance, либо set_to': 'Provide either advance or set_to',
    'Укажите advance или set_to': 'Provide advance or set_to',
    'advance должен быть объектом': 'advance must be an object',
    'advance содержит неподдерживаемые поля': 'advance contains unsupported fields',
    'advance должен быть от 1 минуты до 365 дней': 'advance must be from 1 minute to 365 days',
    'Некорректное set_to время Campaign Clock': 'Invalid set_to Campaign Clock time',
    'Item transfer содержит неподдерживаемые поля': 'Item transfer contains unsupported fields',
    'Неизвестный тип передачи предмета': 'Unknown item transfer type',
    'Некорректный идентификатор предмета': 'Invalid item identifier',
    'Передавать можно только carried предмет (сначала снимите его)': 'Only carried items can be transferred (unequip it first)',
    'Сначала снимите броню из слота': 'Unequip the armor from its slot first',
    'Сначала снимите установленные модификации с предмета': 'Remove installed modifications from the item first',
    'Предмет взят в долг — его можно только вернуть владельцу': 'The item is borrowed — it can only be returned to its owner',
    'Предмет сейчас в долгу у другого персонажа': 'The item is currently loaned out to another character',
    'Некорректное количество для передачи': 'Invalid transfer quantity',
    'Этот предмет передаётся поштучно (не stackable)': 'This item transfers one at a time (not stackable)',
    'Инвентарь получателя переполнен': 'The recipient inventory is full',
    'Делить можно только stackable предметы': 'Only stackable items can be split',
    'Предмет взят в долг — его нельзя делить': 'A borrowed item cannot be split',
    'Для разделения укажите количество меньше размера стека': 'To split, choose an amount smaller than the stack size',
    'Укажите получателя (to_char_id)': 'Provide a recipient (to_char_id)',
    'Нельзя передать предмет самому себе': 'You cannot transfer an item to yourself',
    'Досье получателя заархивировано': 'The recipient Dossier is archived',
    'Досье партнёра заархивировано': 'The trade partner Dossier is archived',
    'Предмет взят в долг — сначала верните владельцу': 'The item is borrowed — return it to its owner first',
    'Предмет не числится за вами как долг': 'The item is not listed as borrowed by you',
    'Досье владельца заархивировано': 'The owner Dossier is archived',
    'Предмет не числится как выданный вами в долг': 'The item is not listed as loaned out by you',
    'Укажите партнёра обмена (to_char_id)': 'Provide a trade partner (to_char_id)',
    'Укажите предмет партнёра (to_instance_id)': 'Provide the partner item (to_instance_id)',
    'Нельзя обменять предмет на самого себя': 'You cannot trade an item with itself',
    'Нельзя обменяться с самим собой': 'You cannot trade with yourself',
    'Dossier партнёра изменён в другой вкладке; обновите страницу': 'The partner Dossier changed in another tab; refresh the page',
    'Crew Stash take содержит неподдерживаемые поля': 'Crew Stash take contains unsupported fields',
    'Предмет не найден в Crew Stash': 'Item not found in the Crew Stash',
    'Недостаточно единиц в Crew Stash': 'Not enough units in the Crew Stash',
    'Этот предмет берётся поштучно (не stackable)': 'This item is taken one at a time (not stackable)',
    'Некорректный JSON импорта': 'Invalid import JSON',
    'Импорт должен быть JSON-объектом': 'Import must be a JSON object',
    'Неизвестный предмет в импорте': 'Unknown item in the import',
    'Market reserve содержит неподдерживаемые поля': 'Market reserve contains unsupported fields',
    'Неизвестный предмет Night Market': 'Unknown Night Market item',
    'Предмет не в текущем Night Market': 'Item is not in the current Night Market',
    'Досье зарезервированного персонажа заархивировано': 'The reserved character Dossier is archived',
    'Fixer request содержит неподдерживаемые поля': 'Fixer request contains unsupported fields',
    'Укажите предмет или название запроса': 'Provide an item or a request name',
    'Неизвестный предмет для запроса': 'Unknown item for the request',
    'Запрос Fixer не найден': 'Fixer request not found',
    'Запрос Fixer уже обработан': 'Fixer request is already resolved',
    'Fixer resolve action: fulfill/decline': 'Fixer resolve action: fulfill/decline',
    'Досье заказчика заархивировано': 'The requester Dossier is archived',
    'Некорректная цена Fixer': 'Invalid Fixer price',
    'Укажите название выдаваемого предмета': 'Provide a name for the granted item',
    'Некорректное количество': 'Invalid quantity',
    'NPC statblock должен быть объектом': 'NPC statblock must be an object',
    'NPC skills должен быть объектом до 200 записей': 'NPC skills must be an object with up to 200 entries',
    'NPC weapons должен быть списком до 30 записей': 'NPC weapons must be a list with up to 30 entries',
    'NPC weapon должен быть объектом': 'NPC weapon must be an object',
    'NPC weapon требует имя': 'NPC weapon requires a name',
    'Recap должен быть объектом': 'Recap must be an object',
    'Recap требует название': 'Recap requires a title',
    'Некорректная дата Recap': 'Invalid Recap date',
    'Recap списки должны быть массивами': 'Recap lists must be arrays',
    'Recap participants должен быть списком': 'Recap participants must be a list',
    'Сессия Recap не найдена': 'Recap session not found',
    'Нет доступа к сессии Recap': 'No access to the Recap session',
    'Нет права связывать Recap с этим контрактом': 'Not allowed to link the Recap to this contract',
    'Нет права связывать Recap с этой сюжетной линией': 'Not allowed to link the Recap to this storyline',
    'Recap не найден': 'Recap not found',
    'Recap не опубликован': 'Recap is not published',
    'Нет права редактировать Recap': 'Not allowed to edit this Recap',
    'Нет права удалять Recap': 'Not allowed to delete this Recap',
    'Downtime activity должен быть объектом': 'Downtime activity must be an object',
    'Неизвестная Downtime activity': 'Unknown Downtime activity',
    'Downtime activities должен быть списком до 12 записей': 'Downtime activities must be a list with up to 12 entries',
    'Downtime start содержит неподдерживаемые поля': 'Downtime start contains unsupported fields',
    'Downtime уже активен': 'Downtime is already active',
    'Неизвестная длительность Downtime': 'Unknown Downtime duration',
    'Downtime action содержит неподдерживаемые поля': 'Downtime action contains unsupported fields',
    'Downtime action: resolve/complete/abandon': 'Downtime action: resolve/complete/abandon',
    'Нет активного Downtime': 'There is no active Downtime',
    'Downtime activity не найдена': 'Downtime activity not found',
    'Downtime activity уже отмечена выполненной': 'Downtime activity is already resolved',
    'Некорректная сумма Hustle': 'Invalid Hustle amount',
    'Некорректное восстановление HP': 'Invalid HP recovery',
    'Локации нужно название': 'Location requires a name',
    'Неизвестный тип локации': 'Unknown location type',
    'Некорректные координаты локации': 'Invalid location coordinates',
    'Локация не найдена': 'Location not found',
    'Некорректный идентификатор локации': 'Invalid location identifier',
    'Локация с таким идентификатором уже существует': 'A location with this identifier already exists',
    'Seed локации можно редактировать только через custom копию': 'Seed locations can only be edited via a custom copy',
    'Seed локации нельзя удалить': 'Seed locations cannot be deleted',
    'Неизвестный статус memorial': 'Unknown memorial status',
    'Memorial требует handle': 'Memorial requires a handle',
    'Персонаж уже помечен memorial': 'The character is already memorialized',
    'Memorial для персонажа уже существует': 'A memorial already exists for this character',
    'Укажите причину memorial': 'Provide a reason for the memorial',
    'Memorial не найден': 'Memorial not found',
    'Укажите причину отмены memorial': 'Provide a reason for restoring the character',
    'Afterlife Legacy должен быть объектом': 'Afterlife Legacy must be an object',
    'Напиток требует название': 'The drink requires a name',
}


def server_error_message(message, language):
    if str(language or '').lower().startswith('ru'):
        return message
    if message in SERVER_ERROR_EN:
        return SERVER_ERROR_EN[message]
    replacements = [
        ('Распродано:', 'Sold out:'),
        ('Зарезервировано для другого персонажа:', 'Reserved for another character:'),
        ('Недостаточно единиц:', 'Not enough units:'),
        ('(доступно ', '(available '),
        ('Неизвестный навык:', 'Unknown Skill:'),
        ('Обязательный навык', 'Required Skill'),
        ('должен быть минимум', 'must be at least'),
        ('при создании допустим уровень', 'allowed Level at creation is'),
        ('укажите конкретную специализацию в скобках', 'provide a specialization in parentheses'),
        ('Неизвестный имплант:', 'Unknown Cyberware:'),
        ('Неизвестный предмет стартовой закупки:', 'Unknown starting item:'),
        ('Неизвестный имплант стартовой закупки:', 'Unknown starting Cyberware:'),
        ('требует:', 'requires:'),
        ('не выбран совместимый host', 'no compatible host selected'),
        ('несовместимый host', 'incompatible host'),
        ('допустима только одна установка', 'only one installation is allowed'),
        ('Закупка превышает основной бюджет', 'Shopping exceeds Main Budget'),
        ('Fashion/Fashionware превышает бюджет', 'Fashion/Fashionware exceeds Style Budget'),
        ('Остаток стартового бюджета рассчитан неверно', 'Starting cash was calculated incorrectly'),
        ('Недопустимое стартовое преимущество роли:', 'Invalid starting Role benefit:'),
        ('Нужно распределить ровно', 'Allocate exactly'),
        ('очка характеристик', 'Characteristic Points'),
        ('очков навыков', 'Skill Points'),
        ('Характеристики импланта', 'Cyberware mechanics for'),
        ('не совпадают с Data Pool', 'do not match the Data Pool'),
        ('не совпадает с Data Pool', 'does not match the Data Pool'),
        ('Недопустимая броня для локации', 'Invalid Armor for location'),
        ('SP брони', 'Armor SP for'),
        ('Штрафы брони', 'Armor penalties for'),
        ('Несовместимая модификация:', 'Incompatible modification:'),
        ('допустимо от', 'allowed range is'),
        (' до ', ' to '),
        ('требуется число', 'must be numeric'),
        ('Неизвестный Skill:', 'Unknown Skill:'),
        ('Неизвестный NPC Skill:', 'Unknown NPC Skill:'),
        ('ожидается список до 500 записей', 'must be a list with no more than 500 entries'),
        ('ожидается объект', 'must be an object'),
        ('Броня', 'Armor'),
        ('отсутствует в Inventory', 'is not present in Inventory'),
        ('Надетая броня', 'Equipped Armor'),
        ('отсутствует в стартовой закупке', 'is missing from starting purchases'),
        ('распределите', 'allocate'),
        ('максимум', 'maximum'),
        ('в specialty', 'in one specialty'),
        ('Некорректный цвет темы:', 'Invalid theme color:'),
        ('Изображение должно быть не больше', 'Image must be no larger than'),
        ('Недостаточно IP: требуется', 'Not enough IP; required:'),
        ('Не хватает €$: нужно', 'Not enough eb; required:'),
        ('есть', 'available'),
        ('ожидается список', 'expected a list'),
        ('до 300 записей', 'up to 300 entries'),
        ('записей', 'entries'),
        ('некорректный parent-pool', 'invalid parent pool'),
        ('распределено', 'allocated'),
        ('при parent-pool', 'with parent pool'),
        ('требуется совместимых hosts:', 'required compatible hosts:'),
        ('Сначала извлеките зависимые Cyberware Options:', 'Uninstall dependent Cyberware Options first:'),
        (': выберите left/right side', ': choose a left/right side'),
        (': сторона ', ': side '),
        (' уже занята', ' is already occupied'),
        (': требуется installation site ', ': requires installation site '),
        ('заполните', 'complete'),
        ('выберите Team Member', 'choose a Team Member'),
        ('недоступный выбор', 'unavailable choice'),
        ('уже на минимальном Level', 'is already at minimum Level'),
        ('Некорректное число в поле контракта:', 'Invalid number in Contract field:'),
        ('Не удалось прочитать резервные копии:', 'Could not read backups:'),
        ('Не удалось создать резервную копию:', 'Could not create backup:'),
        ('Резервная копия не прошла проверку:', 'Backup verification failed:'),
        ('Резервная копия не найдена:', 'Backup not found:'),
        ('Требуется Maker', 'Requires Maker'),
        ('rank 1+ для Tech Maker modification', 'rank 1+ for the Tech Maker modification'),
        ('недопустим для host', 'is not allowed for host'),
        ('Недопустимая операция', 'Invalid operation'),
        ('Tech Maker effect value вне диапазона', 'Tech Maker effect value is outside the range'),
        ('Недопустимое значение', 'Invalid value'),
        (' для ', ' for '),
    ]
    out = str(message)
    for ru, en in replacements:
        out = out.replace(ru, en)
    return out


def theme_contrast(a, b):
    def lum(color):
        values=[int(color[index:index+2],16)/255 for index in (1,3,5)]
        values=[value/12.92 if value<=.03928 else ((value+.055)/1.055)**2.4 for value in values]
        return .2126*values[0]+.7152*values[1]+.0722*values[2]
    x,y=lum(a),lum(b);return (max(x,y)+.05)/(min(x,y)+.05)

def validate_theme(theme):
    color_keys={'bg','bg2','panel','panel2','line','text','muted','primary','secondary','accent','success','danger','warning'}
    for key in color_keys:
        if key in theme and not re.fullmatch(r'#[0-9a-fA-F]{6}', str(theme[key])):
            raise ApiError(400, f'Некорректный цвет темы: {key}')
    bg=str(theme.get('bg') or '#0b0e14');panel=str(theme.get('panel') or '#141a2a');text=str(theme.get('text') or '#d7e3f4')
    if theme_contrast(bg,text)<4.5 or theme_contrast(panel,text)<4.5:
        raise ApiError(400, 'Контраст текста темы должен быть не ниже 4.5:1')

def attach_network_media(conn, user_id, entity_type, entity_id, media_ids, allowed_kinds):
    desired = {str(value or '') for value in media_ids if value}
    validated = []
    for media_id in desired:
        media = conn.execute('SELECT * FROM media WHERE id=?', (media_id,)).fetchone()
        if not media or media['kind'] not in allowed_kinds:
            raise ApiError(400, 'Недопустимое изображение NC//NET')
        already = media['attached_type'] == entity_type and media['attached_id'] == entity_id
        if not already and media['owner_id'] != user_id:
            raise ApiError(403, 'Изображение принадлежит другому аккаунту')
        if media['attached_type'] and not already:
            raise ApiError(409, 'Изображение уже прикреплено')
        validated.append(media_id)
    attached = conn.execute('SELECT * FROM media WHERE attached_type=? AND attached_id=?',
                            (entity_type, entity_id)).fetchall()
    for media in attached:
        if media['id'] not in desired:
            conn.execute('UPDATE media SET attached_type=NULL,attached_id=NULL WHERE id=?',
                         (media['id'],))
    for media_id in validated:
        conn.execute('UPDATE media SET attached_type=?,attached_id=? WHERE id=?',
                     (entity_type, entity_id, media_id))


def atomic_endpoint(fn):
    """Serialize a state-changing endpoint and always roll back on failure."""
    @functools.wraps(fn)
    def wrapped(self, conn, qs, match, body):
        if conn.in_transaction:
            conn.commit()
        conn.execute('BEGIN IMMEDIATE')
        try:
            result = fn(self, conn, qs, match, body)
            if conn.in_transaction:
                conn.commit()
            return result
        except Exception:
            if conn.in_transaction:
                conn.rollback()
            raise
    return wrapped


def q1(v, default=None):
    return v[0] if v else default

def rx(p):
    return re.compile('^' + p + '$')
